spring.application.name=spring-consumer
server.port=0

spring.cloud.function.definition=logConsumer
spring.cloud.stream.function.bindings.logConsumer-in-0=input

spring.cloud.stream.bindings.input.group=spring.io
spring.cloud.stream.bindings.input.destination=events

spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
spring.cloud.stream.rabbit.bindings.input.consumer.containerType=STREAM
#spring.cloud.stream.rabbit.bindings.input.consumer.autoBindDlq=true

# Super Streams

spring.cloud.stream.bindings.input.consumer.instance-count=2
spring.cloud.stream.bindings.input.consumer.concurrency=1
spring.cloud.stream.rabbit.bindings.input.consumer.container-type=STREAM
spring.cloud.stream.rabbit.bindings.input.consumer.super-stream=true

spring.cloud.stream.bindings.input.content-type=application/json
spring.cloud.stream.default.contentType=application/json

# AI

spring.ai.ollama.chat.options.model=gpt-oss:20b