spring.application.name=spring-publisher
server.port=0

spring.cloud.function.definition=eventPublisher

spring.cloud.stream.bindings.output.group=spring.io
spring.cloud.stream.bindings.output.destination=events
spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
spring.cloud.stream.rabbit.bindings.output.consumer.containerType=STREAM
#spring.cloud.stream.rabbit.bindings.output.consumer.autoBindDlq=true

bathSize=10000
subBatchSize=5000
spring.cloud.stream.bindings.eventPublisher-out-0.content-type=application/json
spring.cloud.stream.function.bindings.eventPublisher-out-0=output
spring.cloud.stream.bindings.output.contentType=application/json
spring.cloud.stream.bindings.output.content-type=application/json
spring.cloud.stream.default.content-type=application/json
spring.cloud.stream.default.contentType=application/json


# SUper Streams

spring.cloud.stream.bindings.output.producer.partition-count=2
spring.cloud.stream.bindings.output.producer.partition-key-expression=payload['session']
spring.cloud.stream.rabbit.bindings.output.producer.producer-type=stream-async
spring.cloud.stream.rabbit.bindings.output.producer.super-stream=true
spring.cloud.stream.rabbit.bindings.output.producer.declare-exchange=false
