spring.application.name=spring-publisher
server.port=0

spring.cloud.function.definition=eventPublisher
spring.cloud.stream.function.bindings.eventPublisher-out-0=output

spring.cloud.stream.bindings.output.group=spring.io
spring.cloud.stream.bindings.output.destination=events

spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
spring.cloud.stream.rabbit.bindings.output.consumer.containerType=STREAM
#spring.cloud.stream.rabbit.bindings.output.consumer.autoBindDlq=true
bathSize=10000
subBatchSize=5000


#//                        builder.batchSize(1000);
#//            builder.subEntrySize(100);
#//            builder.batchSize(100000); //734000
#//            builder.subEntrySize(10000);
#
#//            builder.batchSize(1000000); //731000
#//            builder.subEntrySize(100000);
#
#//            builder.batchSize(1000000); //743000
#//            builder.subEntrySize(50000);
#//
#//            builder.batchSize(1000000); //743000
#//            builder.subEntrySize(70000);
